version: "3.9"
services: 
  postgres-container:
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: hieu
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    
  pgadmin-container:
    image: dpage/pgadmin4
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "5050:80"
  
  redis-container: 
    image: redis
    restart: always
    ports:
      - "6379:6379"